--------------------------------------------------------
-- Archivo creado  - viernes-octubre-20-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "BRYANAR_"."CLIENT" 
   (	"ID_CLIENT" NUMBER(11,0), 
	"CLIENT_NAME" VARCHAR2(100 BYTE), 
	"CLIENT_LASTNAME" VARCHAR2(100 BYTE), 
	"CLIENT_EMAIL" VARCHAR2(100 BYTE), 
	"CLIENT_NUMBER" VARCHAR2(100 BYTE), 
	"ID_ROLE" NUMBER(11,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "BRYANAR_"."ROLE" 
   (	"ID_ROLE" NUMBER(11,0), 
	"ROLE_NAME" VARCHAR2(20 BYTE), 
	"ROLE_DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BRYANAR_.CLIENT
SET DEFINE OFF;
Insert into BRYANAR_.CLIENT (ID_CLIENT,CLIENT_NAME,CLIENT_LASTNAME,CLIENT_EMAIL,CLIENT_NUMBER,ID_ROLE) values ('2','Bryan','Arrivasplata','bryanarrivasplata.rojas@gmail.com','997767771','1');
Insert into BRYANAR_.CLIENT (ID_CLIENT,CLIENT_NAME,CLIENT_LASTNAME,CLIENT_EMAIL,CLIENT_NUMBER,ID_ROLE) values ('20','Bryane','Arrivasplata','bryanarrivasplata.rojas@gmail.com','997767771','1');
REM INSERTING into BRYANAR_.ROLE
SET DEFINE OFF;
Insert into BRYANAR_.ROLE (ID_ROLE,ROLE_NAME,ROLE_DESCRIPTION) values ('1','client','Cliente');
Insert into BRYANAR_.ROLE (ID_ROLE,ROLE_NAME,ROLE_DESCRIPTION) values ('2','client-plus','Cliente Jefe');
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BRYANAR_"."CLIENT_PK" ON "BRYANAR_"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BRYANAR_"."ROLE_PK" ON "BRYANAR_"."ROLE" ("ID_ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "BRYANAR_"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "BRYANAR_"."CLIENT" MODIFY ("CLIENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "BRYANAR_"."CLIENT" MODIFY ("CLIENT_LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "BRYANAR_"."CLIENT" MODIFY ("CLIENT_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BRYANAR_"."CLIENT" MODIFY ("CLIENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "BRYANAR_"."CLIENT" MODIFY ("ID_ROLE" NOT NULL ENABLE);
  ALTER TABLE "BRYANAR_"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "BRYANAR_"."ROLE" MODIFY ("ID_ROLE" NOT NULL ENABLE);
  ALTER TABLE "BRYANAR_"."ROLE" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "BRYANAR_"."ROLE" ADD CONSTRAINT "ROLE_PK" PRIMARY KEY ("ID_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "BRYANAR_"."CLIENT" ADD CONSTRAINT "CLIENT_FK_ROLE" FOREIGN KEY ("ID_ROLE")
	  REFERENCES "BRYANAR_"."ROLE" ("ID_ROLE") ENABLE;
